const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5EFE7',
  },
  scrollView: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#3C3C3C',
  },
  // Stats Cards
  statsContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 24,
  },
  statCard: {
    flex: 1,
    backgroundColor: '#F9F5F0',
    borderRadius: 16,
    padding: 16,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#E8DFD3',
  },
  statNumber: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#3C3C3C',
    marginTop: 8,
  },
  statLabel: {
    fontSize: 12,
    color: '#6B7280',
    marginTop: 4,
  },
  // Sections
  section: {
    marginBottom: 24,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#3C3C3C',
  },
  viewAllText: {
    fontSize: 14,
    color: '#6B7280',
  },
  // Collections
  collectionsScroll: {
    paddingLeft: 20,
  },
  collectionCard: {
    width: 160,
    height: 200,
    borderRadius: 16,
    marginRight: 12,
    overflow: 'hidden',
  },
  collectionImage: {
    width: '100%',
    height: '100%',
  },
  collectionImageEmpty: {
    backgroundColor: '#E8DFD3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  collectionOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    padding: 12,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  collectionName: {
    fontSize: 16,
    fontWeight: '600',
    color: 'white',
  },
  collectionCount: {
    fontSize: 12,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },
  emptyCollections: {
    padding: 40,
    alignItems: 'center',
  },
  emptyText: {
    color: '#9CA3AF',
    fontSize: 14,
  },
  // Explore
  emptyExplore: {
    paddingHorizontal: 20,
    paddingVertical: 60,
    alignItems: 'center',
  },
  emptyExploreText: {
    color: '#9CA3AF',
    fontSize: 14,
    marginTop: 12,
  },
  // Gallery Screen
  searchSection: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    gap: 12,
    marginBottom: 7, // Reduced from 16 to 12
  },
  searchBar: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9F5F0',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 14,
    color: '#3C3C3C',
  },
  filterButton: {
    backgroundColor: '#F9F5F0',
    borderRadius: 12,
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Categories
  categoriesScroll: {
    marginBottom: 12, // Changed from 16 to 12
    flexGrow: 0,
    flexShrink: 0, // Keep this!
  },
  categoriesContent: {
    paddingHorizontal: 20,
    gap: 8,
    alignItems: 'center',
  },
  categoryPill: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    backgroundColor: '#F9F5F0',
    marginRight: 8,
    alignSelf: 'flex-start',
    height: 35, // Explicit height
    flexShrink: 0, // NEW: Prevents pill from being compressed
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryPillActive: {
    backgroundColor: '#7D8F69',
  },
  categoryPillText: {
    fontSize: 14,
    color: '#3C3C3C',
    fontWeight: '500',
  },
  categoryPillTextActive: {
    color: 'white',
  },
  // Photos Header
  photosHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 16,
    marginTop: 4, // NEW: Add a small top margin
  },
  photosTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#3C3C3C',
  },
  photosCount: {
    fontSize: 14,
    color: '#6B7280',
  },
  // Gallery Grid
  galleryGrid: {
    paddingHorizontal: 20,
    paddingBottom: 100,
  },
  galleryRow: {
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  galleryItem: {
    width: (Dimensions.get('window').width - 52) / 2,
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    backgroundColor: '#E8DFD3',
  },
  galleryImage: {
    width: '100%',
    height: '100%',
  },
  videoIndicatorGallery: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Empty State
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: 60,
  },
  emptyIconContainer: {
    width: 96,
    height: 96,
    borderRadius: 48,
    backgroundColor: '#F9F5F0',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 16,
  },
  emptyStateTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#3C3C3C',
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  // Upload Button
  uploadButton: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: '#7D8F69',
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  uploadButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  // Create Collection Button
  createCollectionButton: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: '#7D8F69',
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  createCollectionButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  // Collection Creation Screens
  createCollectionContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 40,
  },
  createCollectionIconContainer: {
    alignItems: 'center',
    marginBottom: 40,
  },
  inputSectionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3C3C3C',
    marginBottom: 12,
  },
  collectionNameInput: {
    backgroundColor: '#F9F5F0',
    borderWidth: 1,
    borderColor: '#E8DFD3',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#3C3C3C',
  },
  continueButton: {
    backgroundColor: '#7D8F69',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 24,
  },
  continueButtonDisabled: {
    backgroundColor: '#D1C7B7',
  },
  continueButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  headerDoneText: {
    color: '#7D8F69',
    fontSize: 16,
    fontWeight: '600',
  },
  selectedCountContainer: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: '#F9F5F0',
    borderBottomWidth: 1,
    borderBottomColor: '#E8DFD3',
  },
  selectedCountText: {
    fontSize: 14,
    color: '#3C3C3C',
    fontWeight: '500',
  },
  selectablePhotosGrid: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 100,
  },
  selectablePhotosRow: {
    justifyContent: 'flex-start',
    gap: 8,
    marginBottom: 8,
  },
  selectablePhotoItem: {
    width: (Dimensions.get('window').width - 56) / 3,
    aspectRatio: 1,
    borderRadius: 8,
    overflow: 'hidden',
    position: 'relative',
  },
  selectablePhotoImage: {
    width: '100%',
    height: '100%',
  },
  photoCheckbox: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'white',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoCheckboxSelected: {
    backgroundColor: '#7D8F69',
    borderColor: '#7D8F69',
  },
  importFromCameraButton: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: '#7D8F69',
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  importFromCameraButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  collectionsListContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 100,
  },
  collectionListCard: {
    flexDirection: 'row',
    backgroundColor: '#F9F5F0',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8DFD3',
  },
  collectionListImageContainer: {
    width: 80,
    height: 80,
    borderRadius: 8,
    overflow: 'hidden',
    marginRight: 12,
  },
  collectionListImage: {
    width: '100%',
    height: '100%',
  },
  collectionListImageEmpty: {
    width: '100%',
    height: '100%',
    backgroundColor: '#E8DFD3',
    justifyContent: 'center',
    alignItems: 'center',
  },
  collectionListInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  collectionListName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3C3C3C',
    marginBottom: 4,
  },
  collectionListCount: {
    fontSize: 14,
    color: '#6B7280',
  },
  // Collection Detail Screen
  collectionDetailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
  },
  collectionDetailTitleContainer: {
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  collectionDetailTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#3C3C3C',
  },
  collectionDetailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 20,
    paddingBottom: 100,
    gap: 12,
  },
  collectionDetailPhotoItem: {
    width: (Dimensions.get('window').width - 64) / 3,
    aspectRatio: 1,
    borderRadius: 8,
    overflow: 'hidden',
  },
  collectionDetailPhotoImage: {
    width: '100%',
    height: '100%',
  },
  collectionDetailEmpty: {
    paddingVertical: 60,
    alignItems: 'center',
  },
  collectionSelectionCheckbox: {
  position: 'absolute',
  top: 8,
  right: 8,
  width: 24,
  height: 24,
  borderRadius: 12,
  borderWidth: 2,
  borderColor: 'white',
  backgroundColor: 'rgba(0, 0, 0, 0.3)',
  justifyContent: 'center',
  alignItems: 'center',
},

collectionSelectionCheckboxSelected: {
  backgroundColor: '#7D8F69',
  borderColor: '#7D8F69',
},
  // Add Photo Button & Modal
  addPhotoButton: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: '#7D8F69',
    borderRadius: 12,
    paddingVertical: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addPhotoButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  addOptionsOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
  },
  addOptionsBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  addOptionsModal: {
    backgroundColor: '#F5EFE7',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    paddingHorizontal: 20,
  },
  addOptionsHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#D1C7B7',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  addOptionsTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#3C3C3C',
    marginBottom: 20,
  },
  addOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9F5F0',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8DFD3',
  },
  addOptionIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'rgba(125, 143, 105, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  addOptionText: {
    flex: 1,
  },
  addOptionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3C3C3C',
    marginBottom: 2,
  },
  addOptionSubtitle: {
    fontSize: 13,
    color: '#6B7280',
  },
  // Selection Mode
  cancelSelectionText: {
    fontSize: 16,
    color: '#7D8F69',
    fontWeight: '600',
  },
  selectionCountText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3C3C3C',
  },
  photoSelectionCheckbox: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'white',
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  photoSelectionCheckboxSelected: {
    backgroundColor: '#7D8F69',
    borderColor: '#7D8F69',
  },
  deleteBar: {
    position: 'absolute',
    bottom: 20,
    left: 20,
    right: 20,
    backgroundColor: '#DC2626',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  deleteBarText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  deleteBarButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  deleteBarButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  // Tag Photo Modal
  tagPhotoOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  tagPhotoModal: {
    backgroundColor: '#F5EFE7',
    borderRadius: 24,
    width: '100%',
    maxHeight: '100%',
  },
  tagPhotoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E8DFD3',
  },
  tagPhotoTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#3C3C3C',
  },
  tagPhotoCounter: {
    fontSize: 14,
    color: '#6B7280',
    fontWeight: '500',
  },
  tagPhotoPreview: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#E8DFD3',
  },
  tagPhotoImage: {
    width: '100%',
    height: '100%',
  },
  tagPhotoSection: {
  padding: 20,
  paddingTop: 16, // Reduced padding
},
  tagPhotoScrollSection: {
    maxHeight: 300, // NEW - limits scrollable area
  },
  tagPhotoSelectedTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  tagPhotoSelectedTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#7D8F69',
    paddingLeft: 12,
    paddingRight: 8,
    paddingVertical: 6,
    borderRadius: 12,
    gap: 6,
  },
  tagPhotoSelectedTagText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  tagPhotoQuickAddLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3C3C3C',
    marginBottom: 12,
  },
  tagPhotoTagsScroll: {
    maxHeight: 150,
  },
  tagPhotoTagsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagPhotoTag: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F9F5F0',
    borderWidth: 1,
    borderColor: '#E8DFD3',
  },
  tagPhotoTagDisabled: {
    backgroundColor: '#E8DFD3',
    opacity: 0.5,
  },
  tagPhotoTagText: {
    fontSize: 14,
    color: '#3C3C3C',
    fontWeight: '500',
  },
  tagPhotoTagTextDisabled: {
    color: '#9CA3AF',
  },
  tagPhotoActions: {
    flexDirection: 'row',
    gap: 12,
    padding: 20,
  },
  tagPhotoSkipButton: {
    flex: 1,
    backgroundColor: '#F9F5F0',
    borderWidth: 1,
    borderColor: '#E8DFD3',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  tagPhotoSkipText: {
    color: '#3C3C3C',
    fontSize: 16,
    fontWeight: '600',
  },
  tagPhotoSaveButton: {
    flex: 1,
    backgroundColor: '#7D8F69',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  tagPhotoSaveText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  tagPhotoTagSelected: {
    backgroundColor: '#7D8F69',
    borderColor: '#7D8F69',
  },

  tagPhotoTagTextSelected: {
    color: 'white',
  },
  // Media Detail Screen
  mediaDetailContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  mediaDetailImage: {
    width: '100%',
    height: '100%',
  },
  mediaDetailDarkOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
  },
  mediaDetailTopBar: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    paddingTop: 60,
    paddingHorizontal: 20,
  },
  mediaDetailBackButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  mediaDetailBottomBar: {
    position: 'absolute',
    bottom: 40,
    left: 20,
    right: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  tagsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 20,
  },
  tagsButtonText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  addButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#7D8F69',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  // Tags Sheet
  tagsSheet: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#F5EFE7',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingTop: 12,
    paddingBottom: 40,
    paddingHorizontal: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
  },
  tagsSheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#D1C7B7',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  tagsSheetTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#3C3C3C',
    marginBottom: 16,
  },
  tagsSheetContent: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  tagChip: {
    backgroundColor: '#7D8F69',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
  },
  tagChipText: {
    color: 'white',
    fontSize: 14,
    fontWeight: '500',
  },
  tagsSheetInfo: {
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#E8DFD3',
  },
  tagsSheetCategory: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3C3C3C',
    marginBottom: 4,
  },
  tagsSheetDate: {
    fontSize: 12,
    color: '#6B7280',
  },
  // Add Media Screen
  addMediaContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  addMediaButton: {
    backgroundColor: '#7D8F69',
    borderRadius: 16,
    paddingVertical: 20,
    paddingHorizontal: 40,
    alignItems: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  addMediaButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  // Tag Media Screen
  tagSection: {
    paddingHorizontal: 20,
    marginBottom: 24,
  },
  tagSectionLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3C3C3C',
    marginBottom: 12,
  },
  categorySelect: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F9F5F0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: '#E8DFD3',
  },
  categorySelectText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  categorySelectTextFilled: {
    fontSize: 14,
    color: '#3C3C3C',
    fontWeight: '500',
  },
  categoryDropdown: {
    backgroundColor: '#F9F5F0',
    borderRadius: 12,
    marginTop: 8,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E8DFD3',
  },
  categoryOption: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E8DFD3',
  },
  categoryOptionText: {
    fontSize: 14,
    color: '#3C3C3C',
  },
  tagsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  tagOption: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 12,
    backgroundColor: '#F9F5F0',
    borderWidth: 1,
    borderColor: '#E8DFD3',
  },
  tagOptionSelected: {
    backgroundColor: '#7D8F69',
    borderColor: '#7D8F69',
  },
  tagOptionText: {
    fontSize: 14,
    color: '#3C3C3C',
    fontWeight: '500',
  },
  tagOptionTextSelected: {
    color: 'white',
  },
  importActions: {
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#E8DFD3',
  },
  importButton: {
    backgroundColor: '#7D8F69',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  importButtonDisabled: {
    backgroundColor: '#D1C7B7',
  },
  importButtonText: {
    color: 'white',
    fontSize: 16,
    fontWeight: '600',
  },
  // Tab Bar
  tabBar: {
    backgroundColor: '#F5EFE7',
    borderTopWidth: 1,
    borderTopColor: '#E8DFD3',
    paddingTop: 8,
    paddingBottom: 20,
    height: 80,
  },
  tabBarLabel: {
    fontSize: 11,
    fontWeight: '500',
    marginTop: 2,
  },
  tabBarItem: {
    flex: 1,
  },
  tabBarContainer: {
    backgroundColor: '#F5EFE7',
    borderTopWidth: 1,
    borderTopColor: '#E8DFD3',
  },
  tabBarContent: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingTop: 8,
    paddingBottom: 20,
    height: 80,
  },
  customTabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  customTabLabel: {
    fontSize: 11,
    fontWeight: '500',
    marginTop: 4,
  },
  // Profile Screen
  profileContent: {
  flex: 1,
  justifyContent: 'center',
  alignItems: 'center',
  paddingHorizontal: 20,
},

profileEmail: {
  fontSize: 16,
  color: '#3C3C3C',
  marginTop: 16,
  marginBottom: 32,
},

logoutButton: {
  flexDirection: 'row',
  backgroundColor: '#DC2626',
  paddingHorizontal: 24,
  paddingVertical: 12,
  borderRadius: 12,
  alignItems: 'center',
  gap: 8,
},

logoutButtonText: {
  color: 'white',
  fontSize: 16,
  fontWeight: '600',
},
});